# Copyright (c) Bosch Software Innovations GmbH 2018.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# SPDX-License-Identifier: EPL-2.0
language: java
addons:
  apt:
    packages:
      - git
jdk: openjdk8

before_install:
  - wget -N -O /tmp/install-jdk.sh https://raw.githubusercontent.com/sormuras/bach/ab648ed36892439f49a827cdf18c25e17c8095db/install-jdk.sh
  - chmod +x /tmp/install-jdk.sh
install:
  - ./modules/p2/prepareDependenciesForP2.sh
  - mvn install -DskipTests=true -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  include:
    # compile and execute with the same JDK
    - &mvn-test
      name: mvn test
      script:
        - mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        - cd example-projects/example-project
        - mvn package
    - <<: *mvn-test
      name: mvn test openjdk9
      jdk: openjdk9
    - <<: *mvn-test
      name: mvn test openjdk10
      jdk: openjdk10
    - <<: *mvn-test
      name: mvn test openjdk11
      jdk: openjdk11

    # run static code analysis
    - name: static code analysis
      script:
        - mvn pmd:pmd

    # compile with JDK8 and execute with other JDK
    - &differentJDK-test
      name: mvn test, run with openjdk9
      env:
        - EXECUTION_JDK=9
      script:
        - export JAVA_HOME=$HOME/custom_jdk
        - /tmp/install-jdk.sh -f $EXECUTION_JDK -l GPL --target $JAVA_HOME
        - cd example-projects/example-project
        - mvn package -Dmaven.compiler.source=$EXECUTION_JDK -Dmaven.compiler.target=$EXECUTION_JDK -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - <<: *differentJDK-test
      name: mvn test, run with openjdk10
      env:
        - EXECUTION_JDK=10
    - <<: *differentJDK-test
      name: mvn test, run with openjdk11
      env:
        - EXECUTION_JDK=11

    # test CLI
    - name: cli test
      script:
        - .travis/runCLI.sh example-projects/example-project
        - java -jar core/frontend-stubs-testing/target/antenna-test-project-asserter.jar ExampleTestProject example-projects/example-project/target

    # test Gradle
    - name: gradleTest
      script:
        - cd example-projects/example-project
        - gradle analyze
        - java -jar ../../core/frontend-stubs-testing/target/antenna-test-project-asserter.jar ExampleTestProject build
    
    # test P2
    - name: p2Test
      script:
        - .travis/p2e2etest.sh

    # run site tests (for instance: all links work correctly)
    - name: siteTest
      script:
        - cd antenna-documentation
        - mvn site -Psite-tests

    # Test for license headers
    - name: test for license headers
      before_install: true
      install: true
      script: .travis/testForLicenseHeaders.sh
  allow_failures:
    - name: mvn test openjdk9
    - name: mvn test openjdk10
    - name: mvn test openjdk11
