# Copyright (c) Bosch Software Innovations GmbH 2018
# Copyright (c) Bosch.IO GmbH 2020-2021
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# SPDX-License-Identifier: EPL-2.0

name: Antenna Build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2.3.4

    - name: Cache maven repository
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Cache sonarcloud
      uses: actions/cache@v2.1.4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B clean install -Pcoverage -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - name: Run SCA Analysis
      run: mvn verify -DskipTests pmd:pmd checkstyle:checkstyle-aggregate spotbugs:check

    - name: Run SonarCloud Analysis
      run: mvn sonar:sonar -Dsonar.organization=sw360antenna -Dsonar.projectKey=sw360antenna -Dsonar.host.url=https://sonarcloud.io
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run Example Project Test with JDK8
      run: |
        cd example-projects/example-project
        mvn -B clean verify

    - name: CLI Frontend Test
      run: bash .ci-scripts/test-ExampleTestProject-with-CLI.sh

    - name: Gradle Frontend Test
      run: bash .ci-scripts/test-ExampleTestProject-with-gradle.sh

    - name: p2Test
      run: bash .ci-scripts/test-p2-end2end.sh

    - name: Antenna Documentation Test
      run: bash .ci-scripts/test-antenna-documentation-site-tests.sh

    - name: Test for License Headers
      run: bash .ci-scripts/test-for-licenseHeaders.sh

    - name: Setup JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Test with JDK 11
      run: |
        cd example-projects/example-project
        mvn -B clean verify -Dmaven.compiler.source=11 -Dmaven.compiler.target=11
